export const destinations = [
  {
    name: "Bali",
    banner: "/destinations/bali/pexels-oleksandr-p-2166553.jpg",
    slug: "bali",
    images: [
      "/destinations/bali/pexels-oleksandr-p-2166553.jpg",
      "/destinations/bali/bali-2975787_1920.jpg",
      "/destinations/bali/bali-7969001_1920.jpg",
      "/destinations/bali/sebastian-pena-lambarri-U_i6h9Y50wQ-unsplash.jpg",
      "/destinations/bali/alfiano-sutianto-exFdOWkYBQw-unsplash.jpg",
      "/destinations/bali/real-estate-4955086_1920.jpg",
      "/destinations/bali/real-estate-4955093_1920.jpg",
      "/destinations/bali/villa-4555824_1920.jpg",
    ],
    text1:
      "Bali is an island located in Indonesia, well known for its forest volcanic mountains, beautiful coral reefs and plenties of beaches and resorts. It looks mysterious like the story background of Tomb Raider, thanks to its ancient history and beautiful architectures. According to the official website of Bali, the island has a population of around 4 million of residents.",
  },
  {
    name: "Cape Town",
    banner: "/destinations/capetown/marcreation-99NphH_4F8k-unsplash.jpg",
    slug: "capetown",
    images: [
      "/destinations/capetown/marcreation-99NphH_4F8k-unsplash.jpg",
      "/destinations/capetown/port-7014611_1920.jpg",
      "/destinations/capetown/shashank-kumar-YMOvzRuBH8k-unsplash.jpg",
    ],
    text1:
      "Cape Town, a South Africa's legislative capital, boasts natural beauty with Table Mountain, Cape Point, and stunning beaches. Its rich history dates back to Portuguese exploration, Dutch settlement, and British colonial rule. Modern Cape Town is a cosmopolitan city surrounded by nature, offering diverse cultural experiences and attractions like Groot Constantia wine estate, Kirstenbosch Botanical Garden, and the V&A Waterfront. Contact us for more information.",
  },
  {
    name: "Hokkaido",
    banner: "/destinations/hokkaido/CC6A1410.jpg",
    slug: "hokkaido",
    images: [
      "/destinations/hokkaido/CC6A1410.jpg",
      "/destinations/hokkaido/CC6A1815.jpg",
      "/destinations/hokkaido/P7060496.jpg",
      "/destinations/hokkaido/PB190186.jpg",
      "/destinations/hokkaido/IMG_0082.jpg",
      "/destinations/hokkaido/CC6A1162.jpg",
    ],
    text1: "",
  },
  {
    name: "Machu Picchu",
    banner: "/destinations/machupicchu/peru-2774925_1920.jpg",
    slug: "machupicchu",
    images: [
      "/destinations/machupicchu/peru-2774925_1920.jpg",
      "/destinations/machupicchu/peru-2486831_1920.jpg",
      "/destinations/machupicchu/peru-1880911_1920.jpg",
    ],
    text1: "",
  },
  {
    name: "Maldives",
    banner: "/destinations/maldives/pexels-asad-photo-maldives-1320684.jpg",
    slug: "maldives",
    images: [
      "/destinations/maldives/pexels-asad-photo-maldives-1320684.jpg",
      "/destinations/maldives/beach-666122_1920.jpg",
      "/destinations/maldives/maldives-262511_1920.jpg",
      "/destinations/maldives/maldives-1993704_1920.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-1198839.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-1266831.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-1268855.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-1430676.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-1483054.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-3155657.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-3155662.jpg",
      "/destinations/maldives/pexels-asad-photo-maldives-3155662.jpg",
      "/destinations/maldives/pexels-oleksandr-p-1540108.jpg",
    ],
    text1: "",
  },
  {
    name: "Okinawa",
    banner: "/destinations/okinawa/.jpg",
    slug: "okinawa",
    images: ["/destinations/okinawa/CC6A1410.jpg"],
    text1: "",
  },
  {
    name: "Paris",
    banner: "/destinations/paris/.jpg",
    slug: "paris",
    images: ["/destinations/paris/CC6A1410.jpg"],
    text1: "",
  },
  {
    name: "Santorini",
    banner: "/destinations/santorini/.jpg",
    slug: "santorini",
    images: ["/destinations/santorini/CC6A1410.jpg"],
    text1: "",
  },
  {
    name: "Taipei",
    banner: "/destinations/taipei/.jpg",
    slug: "taipei",
    images: ["/destinations/taipei/CC6A1410.jpg"],
    text1: "",
  },
  {
    name: "Tokyo",
    banner: "/destinations/tokyo/.jpg",
    slug: "tokyo",
    images: ["/destinations/tokyo/CC6A1410.jpg"],
    text1: "",
  },
]
