export const destinations = [
  {
    name: "Bali",
    banner: "/img/bali/pexels-oleksandr-p-2166553.jpg",
    slug: "bali",
    images: [
      "/img/bali/bali-7969001_1920.jpg",
      "/img/bali/bali-2975787_1920.jpg",
      "/img/bali/pexels-oleksandr-p-2166553.jpg",
      "/img/bali/sebastian-pena-lambarri-U_i6h9Y50wQ-unsplash.jpg",
      "/img/bali/alfiano-sutianto-exFdOWkYBQw-unsplash.jpg",
      "/img/bali/real-estate-4955086_1920.jpg",
      "/img/bali/real-estate-4955093_1920.jpg",
      "/img/bali/villa-4555824_1920.jpg",
    ],
    text1:
      "Bali is an island located in Indonesia, well known for its forest volcanic mountains, beautiful coral reefs and plenty of beaches and resorts. It looks mysterious like the story background of Tomb Raider, thanks to its ancient history and beautiful architectures. According to the official website of Bali, the island has a population of around 4 million of residents.",
  },
  {
    name: "Cape Town",
    banner: "/img/capetown/shashank-kumar-YMOvzRuBH8k-unsplash.jpg",
    slug: "capetown",
    images: [
      "/img/capetown/marcreation-99NphH_4F8k-unsplash.jpg",
      "/img/capetown/port-7014611_1920.jpg",
      "/img/capetown/shashank-kumar-YMOvzRuBH8k-unsplash.jpg",
    ],
    text1:
      "Cape Town, the South Africa's legislative capital, boasts natural beauty with Table Mountain, Cape Point, and stunning beaches. Its rich history dates back to Portuguese exploration, Dutch settlement, and British colonial rule. Modern Cape Town is a cosmopolitan city surrounded by nature, offering diverse cultural experiences and attractions like Groot Constantia wine estate, Kirstenbosch Botanical Garden, and the V&A Waterfront. Contact us for more information.",
  },
  {
    name: "Hokkaido",
    banner: "/img/hokkaido/alexchu-furano1.jpg",
    slug: "hokkaido",
    images: [
      "/img/hokkaido/alexchu-furano2.jpg",
      "/img/hokkaido/alexchu-furano3.jpg",
      "/img/hokkaido/alexchu-furano1.jpg",
      "/img/hokkaido/alexchu-otaru-fishmarket.jpg",
      "/img/hokkaido/alexchu-hokkaido-onsen.jpg",
      "/img/hokkaido/alexchu-snowcovered-sapporo.jpg",
    ],
    text1:
      "Hokkaido, the massive island up north in Japan, is a gift of the mother earth to the people which preserves the wild nature with a lot offering. Endless adventures in nature, insane ski slopes, and hot springs to chill out after a long day of exploring. Plus, you can't beat the fresh seafood straight from the sea, those fish markets are insane especially in Otaru. Hokkaido's got that vibe, making it a must-visit for any young traveller looking for an epic time.",
  },
  {
    name: "Machu Picchu",
    banner: "/img/machupicchu/peru-2774925_1920.jpg",
    slug: "machupicchu",
    images: [
      "/img/machupicchu/peru-1880911_1920.jpg",
      "/img/machupicchu/peru-2486831_1920.jpg",
      "/img/machupicchu/peru-2774925_1920.jpg",
    ],
    text1:
      "Have you ever dreamed of trekking through the Peruvian Andes to discover the legendary Machu Picchu? It's like this epic journey that every adventurer dreams about. Imagine hiking through misty mountains, feeling the ancient vibes as you explore those ancient Incan ruins. Machu Picchu isn't just a trip, it's a life-changing experience that'll have you feeling like you've unlocked some ancient secrets.",
  },
  {
    name: "Maldives",
    banner: "/img/maldives/pexels-asad-photo-maldives-1320684.jpg",
    slug: "maldives",
    images: [
      "/img/maldives/pexels-asad-photo-maldives-1483054.jpg",
      "/img/maldives/beach-666122_1920.jpg",
      "/img/maldives/maldives-262511_1920.jpg",
      "/img/maldives/maldives-1993704_1920.jpg",
      "/img/maldives/pexels-asad-photo-maldives-1198839.jpg",
      "/img/maldives/pexels-asad-photo-maldives-1266831.jpg",
      "/img/maldives/pexels-asad-photo-maldives-1268855.jpg",
      "/img/maldives/pexels-asad-photo-maldives-1430676.jpg",
      "/img/maldives/pexels-asad-photo-maldives-1320684.jpg",
      "/img/maldives/pexels-asad-photo-maldives-3155657.jpg",
      "/img/maldives/pexels-asad-photo-maldives-3155662.jpg",
      "/img/maldives/pexels-asad-photo-maldives-3601425.jpg",
      "/img/maldives/pexels-oleksandr-p-1540108.jpg",
    ],
    text1:
      "Nestled in the heart of the Indian Ocean, the Maldives is like a dream come true for anyone craving sun, sea, and sand. Think powder-white beaches, crystal-clear turquoise waters, and overwater bungalows that redefine luxury. It's the perfect playground for young travelers seeking relaxation, adventure, and Instagram-worthy moments. From snorkelling with colourful fish to romantic sunset cruises, the Maldives offers an unforgettable escape for the young and the young at heart. So pack your bags and get ready to experience paradise like never before!",
  },
  {
    name: "Okinawa",
    banner: "/img/okinawa/skaterlunatic-7nHmCuCdY20-unsplash.jpg",
    slug: "okinawa",
    images: [
      "/img/okinawa/ishigaki-3420678_1920.jpg",
      "/img/okinawa/underwater-7559632_1920.jpg",
      "/img/okinawa/underwater-7557528_1920.jpg",
      "/img/okinawa/shop-990443_1920.jpg",
      "/img/okinawa/sea-5450863_1920.jpg",
      "/img/okinawa/lewis-yin--vAZLOQCVXo-unsplash.jpg",
      "/img/okinawa/hawksbill-sea-turtle-6834388_1920.jpg",
      "/img/okinawa/skaterlunatic-7nHmCuCdY20-unsplash.jpg",
      "/img/okinawa/green-turtle-7133765_1920.jpg",
      "/img/okinawa/_DSC9738.jpg",
      "/img/okinawa/_DSC9420.jpg",
      "/img/okinawa/_DSC9244.jpg",
      "/img/okinawa/_DSC9212.jpg",
      "/img/okinawa/_DSC8751.jpg",
    ],
    text1:
      "Okinawa, the southernmost prefecture of Japan, is the East Asian Hawaii. It is quite different from the rest of Japan, with its own mixed culture of Japan, Taiwan, and the US. Okinawa is famous for its stunning beaches, unique Ryukyu culture and history. The food is also amazing, you can find typical Japanese food here, but also Okinawa's unique dishes in addition of Taiwanese and American cuisine. It is one of the best place to do scuba diving.",
  },
  {
    name: "Paris",
    banner: "/img/paris/paris-4353533_1920.jpg",
    slug: "paris",
    images: [
      "/img/paris/pexels-pixabay-2344.jpg",
      "/img/paris/arc-de-triomphe-101633_1280.jpg",
      "/img/paris/alex-harmuth-bOICdD-Gulk-unsplash.jpg",
      "/img/paris/architecture-1850689_1920.jpg",
      "/img/paris/bridge-4345139_1920.jpg",
      "/img/paris/bird-2590901_1920.jpg",
      "/img/paris/paris-4353533_1920.jpg",
      "/img/paris/cafe-4120838_1920.jpg",
      "/img/paris/croissant-5264147_1920.jpg",
      "/img/paris/louvre-5767708_1920.jpg",
      "/img/paris/night-4011992_1920.jpg",
      "/img/paris/paris-813238_1920.jpg",
      "/img/paris/paris-3234472_1920.jpg",
      "/img/paris/paris-4694708_1920.jpg",
      "/img/paris/pexels-pixabay-2363.jpg",
      "/img/paris/pexels-pixabay-460740.jpg",
      "/img/paris/street-2820547_1920.jpg",
      "/img/paris/tony-lee-8IKf54pc3qk-unsplash.jpg",
    ],
    text1:
      "The most luxury brands, the best wines, the most romantic city, the Michellin star restaurants, the best art, the best fashion, the best architecture, almost everything. You know you are in one of the most classy city the time you walk in Paris. Everyone seems so fashionable, so elegant, so romantic. The city is full of history and so artistic, it is so Instagrammable. You just want to slow yourself down and immerse yourself in just any cafe at the corner of the street, and enjoy the moment. It is a city that you can't miss in your life.",
  },
  {
    name: "Santorini",
    banner: "/img/santorini/church-2020258_1920.jpg",
    slug: "santorini",
    images: [
      "/img/santorini/pexels-aleksandar-pasaric-1285625.jpg",
      "/img/santorini/oia-4372096_1920.jpg",
      "/img/santorini/santorin-263346_1920.jpg",
      "/img/santorini/church-2020258_1920.jpg",
      "/img/santorini/santorini-4996846_1920.jpg",
      "/img/santorini/santorini-4996901_1920.jpg",
      "/img/santorini/santorini-5655299_1920.jpg",
    ],
    text1:
      "As the jewel in the Aegean Sea, Santorini is in the bucket list of almost every traveller. The whitewashed buildings perched atop those dramatic cliffs with the azure sea behind, it is just so iconic. With the least effort, you can take a picture like a scene straight out from a postcard. Walking along the narrow cobblestone streets with different shops, witnessing the breathtaking sunset. It is small island but it promises an unforgettable journey. ",
  },
  {
    name: "Taipei",
    banner: "/img/taipei/cityscape-5543223_1920.jpg",
    slug: "taipei",
    images: [
      "/img/taipei/night-market-1714683_1920.jpg",
      "/img/taipei/pexels-kaichieh-chan-2771807.jpg",
      "/img/taipei/pexels-timo-volz-1717859.jpg",
      "/img/taipei/cityscape-5543223_1920.jpg",
      "/img/taipei/taipei-1219394_1920.jpg",
      "/img/taipei/woman-4959896_1920.jpg",
    ],
    text1:
      "Treasure Island is the meaning of Taiwan in the language of the indigenous people. In the capital of Taiwan, Taipei, you will be overwhelmed by the mixture of modernity, history and culture. The city is so energetic, from its bustling night markets, to its peaceful temples, and a lot of modern cafes and restaurants, you will never get bored and hungry. You can also enjoy the hot springs and beautiful landscape in the surrounding area.",
  },
  {
    name: "Tokyo",
    banner: "/img/tokyo/erik-eastman-4HG5hlhmZg8-unsplash.jpg",
    slug: "tokyo",
    images: [
      "/img/tokyo/jaison-lin-2WHTac8jVA8-unsplash.jpg",
      "/img/tokyo/alexchu-tokyoskytree.jpg",
      "/img/tokyo/alexchu-sakura-at-night.jpg",
      "/img/tokyo/alexchu-tokyo-shrine.jpg",
      "/img/tokyo/chef-4807317_1920.jpg",
      "/img/tokyo/gundam-1010971_1920.jpg",
      "/img/tokyo/erik-eastman-4HG5hlhmZg8-unsplash.jpg",
      "/img/tokyo/japan-237658_1920.jpg",
      "/img/tokyo/jezael-melgoza-7H77FWkK_x4-unsplash.jpg",
      "/img/tokyo/jezael-melgoza-layMbSJ3YOE-unsplash.jpg",
      "/img/tokyo/pexels-pixabay-46253.jpg",
      "/img/tokyo/sake-barrels-2559608_1920.jpg",
      "/img/tokyo/shibuya-crossing-923000_1920.jpg",
      "/img/tokyo/takashi-miyazaki-64ajtpEzlYc-unsplash.jpg",
      "/img/tokyo/woman-6805531_1920.jpg",
      "/img/tokyo/lanterns-4732803_1920.jpg",
      "/img/tokyo/pexels-audrey-mari-3421920.jpg",
      "/img/tokyo/pexels-berk-ozdemir-3779201.jpg",
    ],
    text1:
      "Tokyo is the capital of Japan, and is the most popular city that traveller or non-traveller would also love to go. It is a city that never sleeps, with its vibrant nightlife, 24/7 restaurants, Don Quijote, and even convenience stores are full of gems. It is the best place for people love Anime, Manga and video games. It has thousands of great restaurants and shops. It features almost everything that a traveller would love, sakura in spring, fireworks in summer, and the beautiful autumn leaves in autumn.",
  },
]
